### ISSUE TITLE
Grid and Chart layout is not saved when when the layout is changed

### ISSUE THREAD

**Issue by vesnaveen** [DevExpress-Examples/aspxdashboard-how-to-load-and-save-dashboards-from-to-a-database-t386418#1]
I am using Devexpress V2.1.13 version. We are facing an issue when we save the dashboard while moving two charts in middle. I edit an existing dashboard but moving the detailed grid to the bottom and the two charts to the middle.  After saving under a new file name, I display it and the grid is back in the middle. I have to make a video for this 

https://user-images.githubusercontent.com/12605452/126494370-1fd66f16-9310-4aa9-8de9-fa0df0b0c8e8.mp4

**Comment by Stason4eg** [comment]
Hello,

I checked our [online demos](https://demos.devexpress.com/dashboard/?mode=designer&dashboardId=SalesOverview) and they are working fine. It seems that some other factors influence this behavior. Please create a new ticket in the Support Center - [https://devexpress.com/ask](https://devexpress.com/ask) and share a sample project to illustrate the issue.
